### ISSUE TITLE
[Media] Invalid image mime type

### ISSUE THREAD

**Issue by seventhseeker** [elcodi/elcodi#623] opened 2015-03-18 09:58 UTC
Sometimes valid images have the mime type "application/octet-stream".

"ImageManager" does not accept this mime type, and throws an "InvalidImageException":
https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Component/Media/Services/ImageManager.php#L95

Sample image:
![applicationoctetstreamimage](https://cloud.githubusercontent.com/assets/1076699/6706237/f4f5df94-cd5b-11e4-9e84-28ab432dad2b.jpg)

**Comment by javiereguiluz** [comment] 2015-03-18 10:44
The problem is that `application/octet-stream` can be anything, not only images. So you cannot blindly trust this MIME type as valid for images.

In theory, the `image/*` constraint is the only valid way to limit image MIME types (this is the one used by Symfony por example). A possible solution: when receiving an `application/octet-stream` "thing", save it in the filesystem and use PHP functions to get information about the file and verify if it's an image or not.

**Comment by mrzard** [comment] 2015-03-20 09:46
This should be fixed by PR#624

**Comment by rogergros** [comment] 2015-03-23 15:59
Hi @seventhseeker , could you confirm that's already fixed?

**Comment by mmoreram** [comment] 2015-03-26 23:54
ping @seventhseeker

**Comment by seventhseeker** [comment] 2015-03-27 20:32
Hi @rogergros, @mmoreram, sorry for the delay.
Awesome! it works great, thanks very much @mrzard

**Comment by rogergros** [comment] 2015-03-30 07:24
Great :) closing!

**Closed by rogergros** 2015-03-30 07:24 UTC
Labels: Elcodi bug hunting, Media
